export default {
  GET_PLANETS_REQUEST: 'GET_PLANETS_REQUEST',
  GET_PLANETS_SUCCESS: 'GET_PLANETS_SUCCESS',
  GET_PLANET_CODE_SUCCESS: 'GET_PLANET_CODE_SUCCESS',
  ADD_FAVE: 'ADD_FAVE',
  REMOVE_FAVE: 'REMOVE_FAVE',
};
